Crecto/crecto

.gitignore, spec/changeset_spec.cr, spec/spec_helper.cr, src/crecto/changeset.cr, src/crecto/changeset/changeset.cr
Runs on an instance of the class. The proc literal requires that a Bool be returned at all times. This way you know if it passed for failed. The message ends up in a generic "_base" error message field. Theres a potential to create better error objects so that "_base" can be managed better.
Wanted to get this out there first before I go too far.
=> Allows for a way to run generic validations

README.md, spec/repo_spec.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/query.cr, src/crecto/schema.cr
closes #2 
Pass query parameters as separate arguments as per [crystal-pg](https://github.com/will/crystal-pg#typed-querying) to prevent against SQL injection
=> Parameterized queries

spec/repo_spec.cr, src/crecto/repo.cr
weird. in situations where results weren't being returned by #get or #get_by, a `nil?` check wasn't sufficient. Calls to `.to_hash` on the PgResult were resulting in index out of bound errors. Added a check to make sure rows *actually* didn't exist.
=> index out of bounds error when using #get and #get_by

spec/repo_spec.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/repo.cr
Queries are run on the `Repo` class. You can choose between getting back the PG::Result or having crecto cast the result set from PG as an object type.
=> Adds the ability to run aribtrary sql queries. 

.travis.yml, Makefile, README.md, shard.yml, spec/migrate, spec/migrations/pg_users.sql
```
$ make migrate
psql -q postgres://localhost/crecto_development < ./spec/migrations/pg_users.sql
$ make spec
crystal spec
.......................................................
Finished in 33.82 milliseconds
55 examples, 0 failures, 0 errors, 0 pending
$ make all
psql -q postgres://localhost/crecto_development < ./spec/migrations/pg_users.sql
crystal spec
.......................................................
Finished in 33.82 milliseconds
55 examples, 0 failures, 0 errors, 0 pending
```
For the migrations, `PG_URL` needs to be set prior to running the command and the database needs to be created in Postgres.
=> removed micrate as a dependency and added some make commands

src/crecto/adapters/postgres_adapter.cr
=> remove duplicate connection pool

src/crecto.cr
PR will add the below 2 types to `WhereType`
- `Hash(Symbol, Int32 | Int64 | String)`
- `Hash(Symbol, Int64 | String)`
=> Add Hash(with Int64) types to WhereType

src/crecto/schema.cr
For example: 
In table have: name, slug, title, body
Bug fields only defined: name, title
=> Fix to support unstrict mapping

src/crecto/repo.cr
```
Exception: syntax error at or near ")" (PQ::PQError)
0x10c2923c2: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10c292361: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10c292338: *CallStack::new:CallStack at ??
0x10c28acd1: *raise<Exception+>:NoReturn at ??
0x10c419dc2: *DB::Statement+@DB::Statement#perform_query_with_rescue<Array(Array(Bool | Float32 | Float64 | Int32 | Int64 | JSON::Any | String | Time | Nil) | Bool | Float32 | Float64 | Int32 | Int64 | JSON::Any | String | Time | Nil)>:PG::ResultSet at ??
0x10c419d59: *DB::Statement+@DB::Statement#query<Array(Array(Bool | Float32 | Float64 | Int32 | Int64 | JSON::Any | String | Time | Nil) | Bool | Float32 | Float64 | Int32 | Int64 | JSON::Any | String | Time | Nil)>:PG::ResultSet at ??
0x10c443014: …
```
=> Return if preload ids is empty for fix bad SQL.

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/migrations/mysql_migrations.sql, spec/migrations/pg_users.sql, spec/migrations/sqlite3_migrations.sql, spec/schema_spec.cr, src/crecto/changeset/changeset.cr, src/crecto/schema.cr
Currently crecto doesn't update `nil` and `false`, because `Crecto::Schema#to_query_hash` doesn't return `nil` and `false` fields. This is a fix for that. All specs updated.
=> Fix nil updates

src/crecto/query.cr
I was browsing the code and found this small typo. Thanks for writing this! I'm also working on an ORM and it's been helpful to see how you did some things!
=> Fix association typos in Query class

src/crecto/repo/query.cr
See #78 for a detailed look at this issue. In short: `param` was being typed as `String | Nil` instead of the more general `DbValue`, which caused the result of `Hash.zip` to not match the type expected by `@wheres.push`. Explicitly casting `param` up to the `DbValue` type solved this issue.
`Hash.zip` also seemed unnecessary, as there is only a single key-value pair, and it can be written using the Hash literal syntax.
=> Fixes #78. Force `param` to be a `DbValue` in `Query.where`.

spec/repo_spec.cr, spec/schema_spec.cr, src/crecto/errors/association_not_loaded.cr, src/crecto/schema/belongs_to.cr, src/crecto/schema/has_many.cr, src/crecto/schema/has_one.cr
Associations now implement a nilable accessor (`thing?`), as well as a non-nilable one (`thing`). If an association has not been preloaded (or it has been explicitly set to nil), `thing?` will return nil, while `thing` will raise a `Crecto::AssociationNotLoaded`. This seems to be a convention in Crystal, as seen in the standard library with things like `Array#first?` and `Array#first`.
Having these alternatives should simplify usage of associations, particularly `has_many`:
```crystal
users = Repo.all(User, Query.new, preload: [:posts])
user = users[0]
user.posts.not_nil!.each{ } # Fails if `posts` is not loaded
user.posts.as(Array(Post)).each{ } # Fails if `posts` is not loaded
user.posts.not_nil!.each{ } unless user.posts.nil? # Always works, but verbose
user.posts.each{ } # raises …
```
=> Fixes #80. Separate nilable/non-nilable accessors for associations.

spec/repo_spec.cr, src/crecto/repo.cr
closes #82 
Looks like the formatter ran also, some extra spacing in there.
Thanks @faultyserver your solution works great
=> preload Repo#all from `preload: [:association]` option

spec/repo_spec.cr, spec/spec_helper.cr, src/crecto/repo.cr, src/crecto/schema/belongs_to.cr, src/crecto/schema/has_many.cr, src/crecto/schema/has_one.cr
Using `Repo.get` with an instance and an association name was treating `belongs_to` associations as if they were `has_many`s, meaning it was trying to find the queryable's `foreign_key` on the association's table, leading to things like this:
```
user = Repo.get(post, :user)
```
where the query is asking for `users.user_id`, instead of `users.id` with the _value_ of `user_id` from `post`.
This PR adds the private method `Repo.get_association` to deal with each different type of association properly. With this, not only are `belongs_to` associations loading properly, but `has_many`s and `has_one`s are also supported through `Repo.get`:
```
posts = Repo.get(user, :posts)
posts.is_a?(Array(Post)) # => true
```
=> Fix `Repo.get` for associations.

README.md, spec/repo_spec.cr, src/crecto/repo.cr, src/crecto/schema/belongs_to.cr, src/crecto/schema/has_one.cr
For `has_many` and `has_many, through` associations, results with no associated records will now default to `[] of Array(Crecto::Model)` instead of nil. This should ensure that the relationships are never nil, and that the normal accessor (e.g. `user.posts`) will always be an array, and will only raise an error if the association has not been loaded. In other words, this will always work:
```crystal
user = Repo.all(User).first
user.posts # => raises Crecto::AssociationNotLoaded
user = Repo.all(User, preload: [:posts])
user.posts # => always an array, even if it has no entries
```
For nilable `belongs_to` and `has_one` associations, there is no good way to tell if the association is purposefully nil or simply has not been loaded yet.
To help users with nilable associations, the error that …
=> Always set `has_many` association values, better errors for nilable associations.

README.md, spec/repo_spec.cr, src/crecto/repo.cr
`Repo.all)` and `Repo.get` for associations have been removed in favor of making `Repo.get_association` a public method.
Spawned by: https://github.com/Crecto/crecto/pull/87#issuecomment-302892093
=> Make `get_association` public

README.md
I had trouble connecting to Postgres when I first setup crecto. After more time debugging than I care to admit, I realized the port was wrong in the sample config.
Here's a tiny PR to fix that 🙂 .
=> Update Postgres port in README.

spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr
Invalid SQL query is generated when WHERE value array is empty.
```crystal
query = Query
.where(name: [] of String)
users = Repo.all(User, query)
users.size.should eq 0
```
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
0x10432de95: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10432de31: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10432de08: *CallStack::new:CallStack at ??
0x1042f42c1: *raise<Exception>:NoReturn at ??
0x1042f42a1: *raise<String>:NoReturn at ??
0x104966685: *MySql::Connection#handle_err_packet<MySql::ReadPacket>:NoReturn at ??
0x104966a6d: *MySql::Connection#raise_if_err_packet<MySql::ReadPacket>:UInt8 at ??
0x10499b70a: …
```
=> fix WHERE IN query with empty Array

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr
@iambudi
Previously records with string primary keys were failing on delete and update, this fixes that.
=> Add single quote around primary key fields for update and delete queries

shard.yml, src/crecto/repo.cr
closes #114 
@vladfaust I think this should fix the delete connection leak.  Only closing the result set if not in a transaction, thats why the specs were failing.
Updating to crystal-pg 0.13.4 fixes some other issues as well 👍
=> fix delete connection leak

spec/repo_spec.cr, src/crecto/repo.cr
Also close result set on `delete_all`
closes #114
=> fix delete_all leak

CHANGELOG.md, spec/repo_spec.cr, src/crecto/repo.cr
Added `raw_query`, `raw_exec`, and `raw_scalar` to Repo to run queries directly on adapter connection
=> raw adapter queries

spec/schema_spec.cr, src/crecto/changeset/changeset.cr, src/crecto/schema.cr
Previously virtual attributes weren't being validated, this adds validation to virtual attributes.
For example validating the length of a password attribute that doesn't get stored in the database:
```crystal
field :password, String, virtual: true
field :password_confirmation, String, virtual: true
validate_length :password, min: 8
```
=> validate virtual attributes

spec/schema_spec.cr, src/crecto/schema.cr
I just wanted to add a convenience method to get the field without Nil type:
typeof(user.first_name) = (String | Nil)
typeof(user.first_name!) = String
It could shorten my code:
before: full_name = user.first_name.as(String) + " " + user.last_name.as(String)
after: full_name = user.first_name! + " " + user.last_name!
Though developers using this method are responsible for the risk of runtime error.
=> added fields' cast typed methods

src/crecto/db_logger.cr
Recently introduced by https://github.com/Crecto/crecto/commit/1e9bae0966626777f34d1e5e9d79c457cba45991 support of Crystal logger is broken giving following error:
```crystal
in lib/crecto/src/crecto/db_logger.cr:32: undefined method 'level=' for IO::ARGF (compile-time type is (IO | Logger | Nil))
@@log_handler.level = Logger::INFO
```
But changing this line will fix all errors, including integration with [amber framework](https://github.com/amberframework/amber):
```crystal
@@log_handler.as(Logger).level = Logger::INFO
```
=> Fix crystal logger support

src/crecto/db_logger.cr
When using Crecto with Amber framework, DB Logger is yielding error:
```crystal
cast from Amber::Environment::Logger to IO+ failed, at /home/grig191/meinkoin_api/lib/crecto/src/crecto/db_logger.cr:14:11:14 (TypeCastError)
from lib/crecto/src/crecto/db_logger.cr:14:11 in 'log'
from lib/crecto/src/crecto/db_logger.cr:27:7 in 'log'
from lib/crecto/src/crecto/adapters/sqlite3_adapter.cr:16:9 in 'exec_execute'
from lib/crecto/src/crecto/adapters/sqlite3_adapter.cr:49:15 in 'insert'
from lib/crecto/src/crecto/adapters/base_adapter.cr:50:11 in 'run_on_instance'
from lib/crecto/src/crecto/repo.cr:211:17 in 'insert'
from lib/crecto/src/crecto/repo.cr:229:7 in 'insert'
from tmp/1517613624698_console.cr:4:1 in '__crystal_main'
from /usr/share/crystal/src/crystal/main.cr:11:3 in '_crystal_main'
from …
```
=> Changed class checking behaviour

src/crecto/schema.cr
This is useful if you want to update an association, as foreign keys
are stored as a PkeyValue, which are just Ints, but need a special case.
I ran into this when adding/updating an association from Crecto-Admin, observing it did nothing. To this point, it might be worth adding a raise in the else block to prevent doing nothing silently.
=> Allow updating PkeyValues with a hash

shard.yml
Hi @fridgerator !
This PR updates `pg` shard to fix breaking-changes on v0.25.0
Crecto itself still requires some changes
=> Update pg shard dependency

spec/query_spec.cr, spec/repo_spec.cr, spec/transactions_spec.cr, src/crecto/repo.cr, src/crecto/repo/query.cr
Query#preload methods now accept a `query` parameter.  This will query the preload association table.
fixes #170 
@zbaylin
=> Allow queries on preloads

spec/repo_spec.cr, spec/transactions_spec.cr, src/crecto/errors/invalid_changeset.cr, src/crecto/live_transaction.cr, src/crecto/repo.cr
This would allow running transactions like this:
``` crystal
begin
Repo.transaction! do |tx|
user = User.new
user.name = "Jokke"
user = tx.insert!(user).instance
post = Repo.get(post_id)
like = Like.new
like.user = user
like.post = post
tx.insert!(like)
end
rescue error : Exception
respond_with(error: error)
end
```
If anything inside the block raises an error (eg. exclamation mark versions of `create`, `update` or `delete`) the transaction will be rolled back and the error will be re-raised.
=> Live transactions

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr
A Query like this `Query.where("name=? OR name=?", ["fred", "bil"]).where(things: 123)` previously generated sql that looked like this:
`SELECT users.* FROM users WHERE name=? OR name=? AND  users.things=?`
This PR adds parentheses around where statements:
`SELECT users.* FROM users WHERE (name=? OR name=?) AND  (users.things=?)`
=> Add parentheses around grouped where clauses

src/crecto/changeset/changeset.cr
The PR for fixing the required fields checker.
It has added an unnecessary error when the field type is `Bool` and the value is `false`.  
I assume the original purpose of this method is checking that "the field has `value`" so that comparing with `nil` should be appropriate.
e.g.  
```crystal
class Sample < Crecto::Model
schema "samples" do
field :id, String, primary_key: true
field :is_deleted, Bool, default: false
end
end
validate_required [:id, :is_deleted]
```
=> Fix required fields checker to compare with nil

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/query_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/repo/query.cr
The PR for adding the option to write JOIN clause string directly.
It will be useful to query the particular table with the condition related to another table's columns,  
which is difficult to achieve by association features.
I referred to the implementation of `WHERE` clause.  
I don't think the option to pass `params` to fill `?` in the string is so useful here, because in my understanding JOIN query requires to write `table_name.column_name` without single quotations.
=> Allow JOIN clause string

spec/transactions_spec.cr
sorry, i thought i had fixed the problem with the wait until the user is inserted but it turned out to be yet another random success. :( I think to have any value in the travis output we should skip this spec for sqlite for now. If you agree I would add an issue for this so we won't forget about it and hopefully provide a permanent fix in the future.
=> skip randomly failing spec for sqlite

spec/transactions_spec.cr
see #192 
the delete_all spec will also randomly fail.
=> skip randomly failing delete_all spec for sqlite

spec/repo_spec.cr, src/crecto/repo.cr
=> only query preloaded belongs_to relations with ids that aren't nil

src/crecto/schema.cr
Timezone schemas fails for me now that Crystal updated to 0.26.0.
This is an update to use the new Time.parse.
=> update time parse to use local timezone

spec/adapters/postgres_adapter_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/adapters/postgres_adapter.cr
Solution based on this thread from the psql-bugs mailing list: https://www.postgresql.org/message-id/DzifLcHs-9wlp5kq6MPKTxu6zI8s5LhAEaVsrq_NRTuQTkw_EWrogrLgDhQ7i5W-cvaIPig0gH59FzBk7Lwr8FUvV7H0fLOYI8heueaoG1Y%3D%40protonmail.com
The issue here is that postgres 10 changed how queries are parsed, part of which made them more conformant to the SQL spec by requiring a properly-formed row value in UPDATE queries. This change mainly affects single-column row values, where it is now _invalid_ to specify a single column in a parentheses as a row value. Always providing `ROW` in the generated SQL should avoid this and be more future-proof.
=> Fixes #207. Handle single-column updates for postgres 10.x

spec/repo_spec.cr, src/crecto/repo.cr
This fixes problems with preloads and delete_alls on schemas which use
custom names for pk
=> remove hardcoded pknames from repo

src/crecto/schema.cr
fixes #226 
Any `Int64` or `Int32` fields were being cast to `PkeyValue`.  Its been this way for a while and I cant remember why I did this, but there is no way to know this implicit thing is happening and is probably incorrect.
After removing this cast all specs still pass and the issue where a JSON field comes back as a different type no longer happens.
=> don't change the type of int fields

shard.yml, src/crecto/schema/has_many.cr
2 changes. First of all, `has_many` associations were not working. I don't know if this was due to the 0.35.0 update or not, but it seems like the foreign key value needs to be cast to `PkeyValue` no matter what it is.
The second change is just updating the dependencies. I also added the `~>` so that we get patches.
=> Fix has_many; update deps

src/crecto/changeset.cr, src/crecto/repo.cr
This issue (https://github.com/Crecto/crecto/issues/251) mentioned issues with Crystal 0.36 compatibility. This PR resolves them.
Note: I've only tested with sqlite so far. If anyone has a test env setup for Mysql & Postgres and want to test it'd be greatly appreciated! Otherwise I can probably get something setup locally later this week.
=> 0.36 compatibility fixes
