README.md, spec/changeset_spec.cr, spec/spec_helper.cr, src/crecto/changeset.cr
Ruby-like `validates` using current methods and options forwarding
=> Multiple validations

spec/migrations/20161120183426_users.sql, spec/repo_spec.cr, spec/schema_spec.cr, spec/spec_helper.cr, src/crecto.cr, src/crecto/changeset.cr, src/crecto/changeset/changeset.cr, src/crecto/schema.cr
This should take care of issue #6
=> Int64 support

src/crecto/adapters/postgres_adapter.cr, src/crecto/repo.cr
Don't pass connection to each method, just run with connection after the query is built.
=> simplify adapter

src/crecto.cr, src/crecto/schema.cr
Fixes issue #22.
The issue was the equality check for Int64.
=> Int feature bug

src/crecto/adapters/base_adapter.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/postgres_adapter.cr
There was previously a lot of code duplication between the Mysql and Postgres adapters.  I created `BaseAdapter` each adapter module extends from.
=> Adapters refactor

CHANGELOG.md, spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/query.cr
Adds both `DISTINCT` AND `GROUP BY` queries
closes #31
@metacortex
=> DISTINCT and GROUP BY queries

CHANGELOG.md, spec/repo_spec.cr, spec/transactions_spec.cr, src/crecto/repo.cr
closes #43 
* `#get` and `#get_by` will return nil if no record exists (nilable), where `#get!` and `#get_by` will raise an errorif no record exists (not nilable)
=> get! and get_by!

CHANGELOG.md, spec/spec_helper.cr, src/crecto/schema.cr, src/crecto/schema/belongs_to.cr
=> auto set belongs_to foreign key

CHANGELOG.md, README.md, spec/spec_helper.cr, src/crecto.cr, src/crecto/multi.cr, src/crecto/schema.cr, src/crecto/schema/belongs_to.cr
* removed `DbBigInt` alias, just use `PkeyValue` for everything
* force all Int type fields to use `PkeyValue`
=> Merge number field types

.gitignore, .travis.yml, shard.yml, spec/adapters/sqlite3_adapter_spec.cr, spec/migrations/sqlite3_migrations.sql, spec/repo_spec.cr, spec/schema_spec.cr, spec/spec_helper.cr, src/crecto/adapters/sqlite3_adapter.cr, src/crecto/repo.cr
=> SQLite3 Support

spec/repo_spec.cr, src/crecto/schema.cr
=> Apply 'to_utc' only when field is local time

CHANGELOG.md, src/crecto/repo/config.cr, src/crecto/version.cr
=> fixed crecto_db bug

spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr
looks like crystal formatter did its thing too
=> unique parameters in `WHERE IN` queries

spec/repo_spec.cr, src/crecto/repo.cr
=> fixed get! with a query

src/crecto/model.cr, src/crecto/schema.cr
* added `MODEL_FIELDS` to be used as a public class constant (modified via macros)
* added instance method `update_from_hash`, works with `HTTP::Params#to_s`
@faultyserver merging this
=> Crecto admin

.travis.yml, CHANGELOG.md, spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/migrations/mysql_migrations.sql, spec/migrations/pg_users.sql, spec/migrations/sqlite3_migrations.sql, spec/repo_spec.cr, spec/spec_helper.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr, src/crecto/model.cr, src/crecto/repo.cr, src/crecto/schema.cr
fixes #98 
fixes #99 
@jwoertink 👍 
`schema "join_table", primary_key: false do`
=> schema without primary key

src/crecto/repo.cr
I got a bloat on my production until found the issue :smile:
=> doc: note about Repo#query returning ResultSet

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr
=> escape primary key in query

README.md, spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/changeset_spec.cr, spec/migrations/mysql_migrations.sql, spec/migrations/pg_users.sql, spec/migrations/sqlite3_migrations.sql, spec/schema_spec.cr, spec/spec_helper.cr, src/crecto/changeset.cr, src/crecto/changeset/changeset.cr, src/crecto/repo.cr
=> uniqueness constraint

CHANGELOG.md, README.md, spec/schema_spec.cr, spec/spec_helper.cr, src/crecto/schema.cr
=> Default value

CHANGELOG.md, README.md, spec/migrations/pg_migrations.sql, spec/repo_spec.cr, spec/spec_helper.cr, src/crecto.cr, src/crecto/adapters/postgres_adapter.cr, src/crecto/changeset/changeset.cr, src/crecto/schema.cr
=> postgres array types

README.md
Hi @fridgerator 
Crecto readme is awesome, but all code in one code block is a bit difficult to read and link (share to other people)
This PR tries to make Crecto's README a bit more readable and shareable using headers permalinks
See proposed README here: https://github.com/faustinoaq/crecto/tree/patch-1#crecto
=> Split README in sections to improve readability

spec/mult_spec.cr, src/crecto/multi.cr, src/crecto/repo.cr
This simplifies the handling of transactions quite a lot IMO. I also think using structs instead of named tuples is more legible and robust.
Please wait for #141 and #142
=> Multi refactoring

spec/migrations/mysql_migrations.sql, spec/migrations/pg_migrations.sql, spec/migrations/sqlite3_migrations.sql, spec/schema_spec.cr, spec/spec_helper.cr, src/types.cr
@jwoertink made a copy of your branch locally just to fix the sqlite migration
=> Jwoertink master

spec/migrations/mysql_migrations.sql, spec/migrations/pg_migrations.sql, spec/migrations/sqlite3_migrations.sql, spec/schema_spec.cr, spec/spec_helper.cr, src/types.cr
fixes #145 
This allows foreign keys and primary keys to be a String. I wanted to add some specs, but I may have gone a little left field with them. I only added the postgres specs, but if you want mysql and sqlite, I can add those in.
=> added String to the PkeyValue union

README.md
This PR only updates the README with some additional info.
* Updated URL to micrate
* Added a reference use join in Query
* Mention of the default fields
* Mention of changing default fields
I would like to re-organize the entire file in to more coherent thoughts, but this at least gets the info out there. Or maybe we write out some wiki pages?
=> Adding some docs

spec/changeset_spec.cr, spec/migrations/pg_migrations.sql, src/crecto/changeset/changeset.cr, src/crecto/schema.cr
=> fixed unique constraint on primary key fields

spec/migrations/mysql_migrations.sql, spec/migrations/pg_migrations.sql, spec/migrations/sqlite3_migrations.sql, spec/repo_spec.cr, spec/spec_helper.cr, spec/transactions_spec.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr, src/crecto/repo.cr
=> fixes inserts of records with no pkey

spec/model_spec.cr, src/crecto/model.cr, src/crecto/schema.cr
=> use JSON::Serializable for json mapping

src/crecto/adapters/base_adapter.cr
=> ensure logging of query strings also on errors

spec/transactions_spec.cr
This should fix the failing spec for sqlite
=> work around for race condition in transaction spec for sqlite

spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr
=> Or where fix

spec/repo_spec.cr, src/crecto/repo.cr
Adds overloads for using get_by and get_by! with query objects
=> Get by query

spec/repo_spec.cr, src/crecto/repo.cr
=> support preloads for Repo#get_by by using Repo#all under the hood

src/crecto/schema.cr
Use Time.parse! as discussed here
https://github.com/Crecto/crecto/pull/209#issuecomment-420870607
=> use prase that does not require Time::Location.local

spec/model_spec.cr, src/crecto/model.cr, src/crecto/schema.cr
=> add mass assignment setter and initializer

spec/adapters/mysql_adapter_spec.cr, spec/adapters/postgres_adapter_spec.cr, spec/adapters/sqlite3_adapter_spec.cr, spec/query_spec.cr, spec/repo_spec.cr, src/crecto/adapters/base_adapter.cr, src/crecto/adapters/mysql_adapter.cr, src/crecto/adapters/sqlite3_adapter.cr, src/crecto/repo/query.cr
- Introduce "where expressions" which can be combined similarily like
boolean expressions
- Add `#and` and `#or` methods to query for grouping
Fixes #200
=> enable grouping of wheres

CHANGELOG.md, shard.yml, src/crecto/version.cr
=> bump version to 0.11.2

.gitlab-ci.yml, Dockerfile, bin/specs, docker-compose.yml, spec/migrations/mysql_migrations.sql, spec/migrations/pg_migrations.sql
I haven't changed travis-ci to use this method yet, however it works locally.
`docker-compose up` to run specs against all 3 databases.
=> can use docker-compose to run specs against 3 databases

docker-compose.yml, src/crecto/db_logger.cr
Also:
fix: Make docker-compose postgres test working
=> fix: Remove Logger deprecation warning

Dockerfile, README.md, src/crecto/repo/config.cr, src/types.cr
Includes README updates and support for additional primary key types. Closes #199.
=> small updates
